a = int(input("enter number "))
b = int(input("enter number two "))
print(f"{a + b}")
print(f"{a - b}")
print(f"{a * b}")
print(f"{a / b}")
print(f"{a ** b}")
print(f"{a + b * a}")
print(f"{(a + b) * b}")
print(f"{a == b}")
print(f"{a < b}")
print(f"{a > b}")
print(f"{a != b}")
print(f"{a <= b}")
print(f"{a >= b}")

